import type { Template, Task, SourceFile, ExtractedCell } from '@/types'

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 'tpl-001',
    route_name: '俄罗斯',
    template_file_url: '/templates/russia.xlsx',
    sheet_name: 'Sheet1',
    header_row_index: 1,
    columns: ['起运港', '目的港', '船东', '船名航次', '截关日', '开航日', '航线代码', '航程(天)', '币别', '20GP底价', '40GP底价', '40HQ底价', '45HQ底价', '40RH底价', '40NOR底价', '20GP指导价', '40GP指导价', '40HQ指导价', '中转/直航', '中转港', '有效期', '备注', '舱位状态', '价格来源'],
    version: 'current',
    created_at: '2025-12-01T08:00:00Z',
    updated_at: '2025-12-01T08:00:00Z',
  },
  {
    id: 'tpl-002',
    route_name: '澳新',
    template_file_url: '/templates/australia.xlsx',
    sheet_name: 'Sheet1',
    header_row_index: 1,
    columns: ['起运港', '目的港', '船东', '船名航次', '截关日', '开航日', '航线代码', '航程(天)', '币别', '20GP底价', '40GP底价', '40HQ底价', '有效期', '备注', '舱位状态'],
    version: 'current',
    created_at: '2025-11-15T08:00:00Z',
    updated_at: '2025-11-15T08:00:00Z',
  },
  {
    id: 'tpl-003',
    route_name: '南太',
    template_file_url: '/templates/south-pacific.xlsx',
    sheet_name: 'Sheet1',
    header_row_index: 1,
    columns: ['起运港', '目的港', '船东', '船名航次', '截关日', '开航日', '币别', '20GP底价', '40GP底价', '40HQ底价', '有效期', '备注'],
    version: 'current',
    created_at: '2025-11-20T08:00:00Z',
    updated_at: '2025-11-20T08:00:00Z',
  },
  {
    id: 'tpl-004',
    route_name: '红海',
    template_file_url: '/templates/red-sea.xlsx',
    sheet_name: 'Sheet1',
    header_row_index: 1,
    columns: ['起运港', '目的港', '船东', '船名航次', '截关日', '开航日', '航线代码', '币别', '20GP底价', '40GP底价', '40HQ底价', '45HQ底价', '中转港', '有效期', '备注', '舱位状态'],
    version: 'current',
    created_at: '2025-10-10T08:00:00Z',
    updated_at: '2026-01-05T08:00:00Z',
  },
]

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-001',
    template_id: 'tpl-001',
    template: MOCK_TEMPLATES[0],
    status: 'review',
    risk_count_red: 2,
    risk_count_yellow: 5,
    created_at: '2026-03-03T09:15:00Z',
    updated_at: '2026-03-03T09:18:00Z',
  },
  {
    id: 'task-002',
    template_id: 'tpl-002',
    template: MOCK_TEMPLATES[1],
    status: 'done',
    risk_count_red: 0,
    risk_count_yellow: 1,
    output_file_url: '/output/task-002.xlsx',
    created_at: '2026-03-02T14:30:00Z',
    updated_at: '2026-03-02T14:35:00Z',
  },
  {
    id: 'task-003',
    template_id: 'tpl-003',
    template: MOCK_TEMPLATES[2],
    status: 'processing',
    risk_count_red: 0,
    risk_count_yellow: 0,
    created_at: '2026-03-03T10:00:00Z',
    updated_at: '2026-03-03T10:01:00Z',
  },
  {
    id: 'task-004',
    template_id: 'tpl-004',
    template: MOCK_TEMPLATES[3],
    status: 'failed',
    risk_count_red: 0,
    risk_count_yellow: 0,
    created_at: '2026-03-01T11:00:00Z',
    updated_at: '2026-03-01T11:02:00Z',
  },
  {
    id: 'task-005',
    template_id: 'tpl-001',
    template: MOCK_TEMPLATES[0],
    status: 'done',
    risk_count_red: 1,
    risk_count_yellow: 3,
    output_file_url: '/output/task-005.xlsx',
    created_at: '2026-02-28T16:00:00Z',
    updated_at: '2026-02-28T16:08:00Z',
  },
]

export const MOCK_SOURCE_FILES: SourceFile[] = [
  { id: 'sf-001', task_id: 'task-001', file_name: '俄罗斯运价表_MSK_2026Q1.pdf', file_type: 'pdf', file_url: '', page_count: 3, created_at: '2026-03-03T09:15:00Z' },
  { id: 'sf-002', task_id: 'task-001', file_name: '船期确认图片.jpg', file_type: 'image', file_url: '', created_at: '2026-03-03T09:15:00Z' },
  { id: 'sf-003', task_id: 'task-001', file_name: '附加费说明.docx', file_type: 'docx', file_url: '', created_at: '2026-03-03T09:15:00Z' },
]

// Mock extracted cells for task-001 (俄罗斯航线，3行数据)
export const MOCK_EXTRACTED_CELLS: ExtractedCell[] = [
  // Row 1
  { id: 'ec-001', task_id: 'task-001', row_index: 1, column_key: '起运港', value: '青岛', risk_level: 'none', confidence: 0.99, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-002', task_id: 'task-001', row_index: 1, column_key: '目的港', value: '弗拉迪沃斯托克', risk_level: 'none', confidence: 0.97, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-003', task_id: 'task-001', row_index: 1, column_key: '船东', value: 'FESCO', risk_level: 'none', confidence: 0.98, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-004', task_id: 'task-001', row_index: 1, column_key: '船名航次', value: 'FESCO YANINA 033W', risk_level: 'none', confidence: 0.95, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-005', task_id: 'task-001', row_index: 1, column_key: '截关日', value: '2026-03-08', risk_level: 'none', confidence: 0.96, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-006', task_id: 'task-001', row_index: 1, column_key: '开航日', value: '2026-03-10', risk_level: 'none', confidence: 0.96, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-007', task_id: 'task-001', row_index: 1, column_key: '航线代码', value: 'RCX', risk_level: 'none', confidence: 0.9, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-008', task_id: 'task-001', row_index: 1, column_key: '航程(天)', value: '4', risk_level: 'none', confidence: 0.99, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-009', task_id: 'task-001', row_index: 1, column_key: '币别', value: 'USD', risk_level: 'none', confidence: 0.99, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-010', task_id: 'task-001', row_index: 1, column_key: '20GP底价', value: '450', risk_level: 'none', confidence: 0.97, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-011', task_id: 'task-001', row_index: 1, column_key: '40GP底价', value: '900', risk_level: 'yellow', confidence: 0.72, is_manually_edited: false, note: '识别把握度较低，请人工核对', created_at: '', updated_at: '' },
  { id: 'ec-012', task_id: 'task-001', row_index: 1, column_key: '40HQ底价', value: '950', risk_level: 'none', confidence: 0.96, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-013', task_id: 'task-001', row_index: 1, column_key: '45HQ底价', value: '', risk_level: 'yellow', confidence: 0, is_manually_edited: false, note: '未在文件中找到，已留空', created_at: '', updated_at: '' },
  { id: 'ec-014', task_id: 'task-001', row_index: 1, column_key: '40RH底价', value: '1200', risk_level: 'none', confidence: 0.94, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-015', task_id: 'task-001', row_index: 1, column_key: '40NOR底价', value: '', risk_level: 'red', confidence: 0, is_manually_edited: false, note: '必填字段缺失，请手动填入', created_at: '', updated_at: '' },
  { id: 'ec-016', task_id: 'task-001', row_index: 1, column_key: '20GP指导价', value: '520', risk_level: 'none', confidence: 0.95, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-017', task_id: 'task-001', row_index: 1, column_key: '40GP指导价', value: '1050', risk_level: 'none', confidence: 0.93, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-018', task_id: 'task-001', row_index: 1, column_key: '40HQ指导价', value: '1100', risk_level: 'none', confidence: 0.93, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-019', task_id: 'task-001', row_index: 1, column_key: '中转/直航', value: '直航', risk_level: 'none', confidence: 0.99, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-020', task_id: 'task-001', row_index: 1, column_key: '中转港', value: '', risk_level: 'none', confidence: 1, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-021', task_id: 'task-001', row_index: 1, column_key: '有效期', value: '2026-03-31', risk_level: 'none', confidence: 0.95, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-022', task_id: 'task-001', row_index: 1, column_key: '备注', value: '', risk_level: 'none', confidence: 1, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-023', task_id: 'task-001', row_index: 1, column_key: '舱位状态', value: '充足', risk_level: 'none', confidence: 0.9, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-024', task_id: 'task-001', row_index: 1, column_key: '价格来源', value: '俄罗斯运价表_MSK_2026Q1.pdf', risk_level: 'none', confidence: 1, is_manually_edited: false, created_at: '', updated_at: '' },

  // Row 2
  { id: 'ec-101', task_id: 'task-001', row_index: 2, column_key: '起运港', value: '上海', risk_level: 'none', confidence: 0.99, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-102', task_id: 'task-001', row_index: 2, column_key: '目的港', value: '圣彼得堡', risk_level: 'none', confidence: 0.96, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-103', task_id: 'task-001', row_index: 2, column_key: '船东', value: 'MSC', risk_level: 'none', confidence: 0.99, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-104', task_id: 'task-001', row_index: 2, column_key: '船名航次', value: 'MSC AURORA 012E', risk_level: 'none', confidence: 0.94, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-105', task_id: 'task-001', row_index: 2, column_key: '截关日', value: '2026-03-12', risk_level: 'none', confidence: 0.97, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-106', task_id: 'task-001', row_index: 2, column_key: '开航日', value: '2026-03-15', risk_level: 'none', confidence: 0.97, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-107', task_id: 'task-001', row_index: 2, column_key: '航线代码', value: 'RBX', risk_level: 'none', confidence: 0.88, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-108', task_id: 'task-001', row_index: 2, column_key: '航程(天)', value: '22', risk_level: 'none', confidence: 0.99, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-109', task_id: 'task-001', row_index: 2, column_key: '币别', value: 'USD', risk_level: 'none', confidence: 0.99, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-110', task_id: 'task-001', row_index: 2, column_key: '20GP底价', value: '1200', risk_level: 'red', confidence: 0.6, is_manually_edited: false, note: '字段冲突：PDF来源为1200，图片来源为1050，请人工确认', created_at: '', updated_at: '' },
  { id: 'ec-111', task_id: 'task-001', row_index: 2, column_key: '40GP底价', value: '2200', risk_level: 'none', confidence: 0.95, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-112', task_id: 'task-001', row_index: 2, column_key: '40HQ底价', value: '2300', risk_level: 'none', confidence: 0.95, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-113', task_id: 'task-001', row_index: 2, column_key: '45HQ底价', value: '2500', risk_level: 'none', confidence: 0.9, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-114', task_id: 'task-001', row_index: 2, column_key: '40RH底价', value: '3200', risk_level: 'none', confidence: 0.92, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-115', task_id: 'task-001', row_index: 2, column_key: '40NOR底价', value: '3500', risk_level: 'none', confidence: 0.91, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-116', task_id: 'task-001', row_index: 2, column_key: '20GP指导价', value: '1400', risk_level: 'none', confidence: 0.93, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-117', task_id: 'task-001', row_index: 2, column_key: '40GP指导价', value: '2500', risk_level: 'none', confidence: 0.93, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-118', task_id: 'task-001', row_index: 2, column_key: '40HQ指导价', value: '2600', risk_level: 'none', confidence: 0.92, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-119', task_id: 'task-001', row_index: 2, column_key: '中转/直航', value: '中转', risk_level: 'none', confidence: 0.99, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-120', task_id: 'task-001', row_index: 2, column_key: '中转港', value: '汉堡', risk_level: 'yellow', confidence: 0.75, is_manually_edited: false, note: '识别把握度较低，请核对', created_at: '', updated_at: '' },
  { id: 'ec-121', task_id: 'task-001', row_index: 2, column_key: '有效期', value: '2026-04-15', risk_level: 'none', confidence: 0.96, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-122', task_id: 'task-001', row_index: 2, column_key: '备注', value: '仅含基本海运费', risk_level: 'none', confidence: 0.88, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-123', task_id: 'task-001', row_index: 2, column_key: '舱位状态', value: '紧张', risk_level: 'none', confidence: 0.85, is_manually_edited: false, created_at: '', updated_at: '' },
  { id: 'ec-124', task_id: 'task-001', row_index: 2, column_key: '价格来源', value: '俄罗斯运价表_MSK_2026Q1.pdf', risk_level: 'none', confidence: 1, is_manually_edited: false, created_at: '', updated_at: '' },
]
